import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import path from "node:path";
import fs from "node:fs";
import manifest from './manifest.json' with { type: 'json' };

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// --- live refresh setup
const vaultFolder = "/media/win/#blackhole/"
const pluginFolder = path.resolve(vaultFolder, ".obsidian", "plugins", manifest.id)
const hotreloadPath = path.resolve(pluginFolder, '.hotreload')
const copyCandidates = ['styles.css', 'main.js', 'manifest.json']
	.map(f => ({ 
		bare: f,
		src: path.resolve(import.meta.dirname, f),
		dest: path.resolve(pluginFolder, f)
	}))

const vaultExists = fs.existsSync(vaultFolder)
if (vaultExists) {	
	fs.mkdirSync(pluginFolder, { recursive: true });
	fs.writeFileSync(hotreloadPath, '', { flag: 'a' }) // no-op if .hotreload exists
}

/** @type {import('esbuild').BuildOptions} */
const config = {
	banner: {
		js: banner,
	},
	entryPoints: {
		main: "src/main.ts",
		styles: "src/styles.css"
	},
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: "./",
	minify: prod,
	plugins: [
		{
			name: 'copy-to-vault',
			setup(build) {
				build.onEnd(r => {
					if (!vaultExists) {
						console.log(`vault folder ${vaultFolder} doesn't exist, skipping copy step...`);
						return;
					}
					if (r.errors.length > 0) {
						console.error(r.errors.join("\n")); 
						return;
					}
					copyCandidates.forEach(({ src, dest }) => {
						if (!fs.existsSync(src)) {
							console.error(`file ${src} doesn't exist! skipping copy...`);
							return; 
						}
						fs.copyFileSync(src, dest)
					})
				})
			}
				}
	]
}

const context = await esbuild.context(config);

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
